//! Core value types shared by all provider adapters.

use serde::{Deserialize, Serialize};

/// The role of a message participant in a conversation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// A system-level instruction message.
    System,
    /// A message from the human user.
    User,
    /// A message generated by the assistant.
    Assistant,
    /// A message produced by a tool invocation.
    Tool,
}

impl Role {
    /// Returns a static string representation of the role.
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::System => "system",
            Self::User => "user",
            Self::Assistant => "assistant",
            Self::Tool => "tool",
        }
    }
}

/// A single message in a conversation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Message {
    /// The role of the entity that produced this message.
    pub role: Role,
    /// The text content of this message.
    pub content: String,
}

impl Message {
    /// Creates a new system message.
    #[must_use]
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: Role::System,
            content: content.into(),
        }
    }

    /// Creates a new user message.
    #[must_use]
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: content.into(),
        }
    }

    /// Creates a new assistant message.
    #[must_use]
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: Role::Assistant,
            content: content.into(),
        }
    }
}

/// Options controlling a single chat-completion call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CallOptions {
    /// The model identifier to use (e.g. `"gpt-4o"`, `"claude-opus-4-5"`).
    pub model: String,
    /// Maximum number of tokens to generate.
    pub max_tokens: Option<u32>,
    /// Sampling temperature in the range `[0.0, 2.0]`.
    pub temperature: Option<f32>,
    /// A separate system prompt sent outside of the messages array.
    ///
    /// Anthropic requires the system prompt to be a top-level field.
    /// `OpenAI` providers prepend it as a `Role::System` message instead.
    pub system: Option<String>,
    /// MCP tool definitions to expose to the model during this call.
    ///
    /// Each element must be a valid JSON object conforming to the provider's
    /// tool-schema format (Anthropic `tools` array, `OpenAI` `functions` array,
    /// etc.). Providers that do not yet support tool injection may ignore this
    /// field.
    pub tools: Option<Vec<serde_json::Value>>,
    /// Provider-native session identifier used by CLI adapters that support
    /// resume semantics.
    pub provider_session_id: Option<String>,
    /// Number of leading messages (after the system prompt) that form the
    /// stable KV-cache prefix.
    ///
    /// When set, providers that support prompt caching (Anthropic) will mark
    /// the system prompt, the last tool definition, and the message at index
    /// `stable_prefix_len - 1` with a cache-control hint.  `Some(0)` caches
    /// only the system prompt and tools; `None` disables cache hints entirely.
    pub stable_prefix_len: Option<usize>,
    /// Provider-neutral cache strategy describing how the routed adapter should
    /// realise the stable-prefix hint.
    ///
    /// Defaults to [`CacheStrategy::None`] (a no-op). The Anthropic path is
    /// driven by `stable_prefix_len` and is unaffected by this field; `OpenAI` and
    /// Gemini consult it to emit `prompt_cache_key` / `cachedContent` respectively.
    #[serde(default)]
    pub cache_strategy: CacheStrategy,
}

/// Provider-neutral instruction for how an adapter should realise a cache hint.
///
/// The orchestrator selects a variant from the routed runner; each adapter
/// honours only the variants it understands and ignores the rest.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CacheStrategy {
    /// No cache strategy; adapters emit their default body.
    #[default]
    None,
    /// Anthropic ephemeral cache-control breakpoints (driven by
    /// `stable_prefix_len`; this variant is purely descriptive).
    AnthropicEphemeral,
    /// `OpenAI` automatic prompt caching with an optional `prompt_cache_key`.
    OpenAiAutomatic {
        /// Optional stable key that scopes automatic caching to a session.
        cache_key: Option<String>,
    },
    /// Gemini explicit context caching referencing a `cachedContent` resource.
    GeminiContext {
        /// Resource name of a previously-created `cachedContent`, when available.
        cached_content: Option<String>,
    },
}

/// A single unit of streamed output from a provider.
#[derive(Debug, Clone, PartialEq)]
pub enum Delta {
    /// Incremental text emitted by the model.
    Text(String),
    /// Provider-native tool invocation emitted by an agentic CLI.
    ToolCall {
        /// Tool name.
        name: String,
        /// Raw provider input payload.
        input: serde_json::Value,
    },
    /// Provider-native tool result emitted by an agentic CLI.
    ToolResult {
        /// Provider tool-use identifier, when supplied.
        tool_use_id: String,
        /// Result content rendered as text.
        content: String,
    },
    /// Provider-native session ID that can be used to resume future turns.
    SessionId(String),
    /// Token-usage statistics emitted at the end of the stream.
    Usage {
        /// Number of tokens in the prompt / input.
        input_tokens: u32,
        /// Number of tokens generated in the response.
        output_tokens: u32,
        /// Provider-reported `gen_ai.usage.cache_read_input_tokens` — input
        /// served from the provider prompt cache and therefore not re-paid.
        /// `0` when the provider reports no cache read or does not report one
        /// (e.g. CLI adapters that do not surface cache counts).
        cache_read_tokens: u32,
    },
}

#[cfg(test)]
mod tests {
    use super::{CacheStrategy, CallOptions};

    fn opts() -> CallOptions {
        CallOptions {
            model: "m".to_owned(),
            max_tokens: None,
            temperature: None,
            system: None,
            tools: None,
            provider_session_id: None,
            stable_prefix_len: None,
            cache_strategy: CacheStrategy::None,
        }
    }

    #[test]
    fn cache_strategy_defaults_to_none() {
        assert_eq!(CacheStrategy::default(), CacheStrategy::None);
    }

    #[test]
    fn call_options_carries_cache_strategy_and_stable_prefix_len() {
        let o = opts();
        assert_eq!(o.cache_strategy, CacheStrategy::None);
        assert!(o.stable_prefix_len.is_none());
    }

    #[test]
    fn cache_strategy_deserializes_with_default_when_field_absent() {
        // A body without `cache_strategy` must still deserialize, defaulting to None.
        let json = r#"{"model":"m","max_tokens":null,"temperature":null,"system":null,"tools":null,"provider_session_id":null,"stable_prefix_len":null}"#;
        let parsed: CallOptions = serde_json::from_str(json).expect("must deserialize");
        assert_eq!(parsed.cache_strategy, CacheStrategy::None);
    }
}
