//! Core value types shared by all provider adapters.

use serde::{Deserialize, Serialize};

/// The role of a message participant in a conversation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// A system-level instruction message.
    System,
    /// A message from the human user.
    User,
    /// A message generated by the assistant.
    Assistant,
    /// A message produced by a tool invocation.
    Tool,
}

impl Role {
    /// Returns a static string representation of the role.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::System => "system",
            Self::User => "user",
            Self::Assistant => "assistant",
            Self::Tool => "tool",
        }
    }
}

/// A single message in a conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// The role of the entity that produced this message.
    pub role: Role,
    /// The text content of this message.
    pub content: String,
}

/// Options controlling a single chat-completion call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CallOptions {
    /// The model identifier to use (e.g. `"gpt-4o"`, `"claude-opus-4-5"`).
    pub model: String,
    /// Maximum number of tokens to generate.
    pub max_tokens: Option<u32>,
    /// Sampling temperature in the range `[0.0, 2.0]`.
    pub temperature: Option<f32>,
    /// A separate system prompt sent outside of the messages array.
    ///
    /// Anthropic requires the system prompt to be a top-level field.
    /// `OpenAI` providers prepend it as a `Role::System` message instead.
    pub system: Option<String>,
    /// MCP tool definitions to expose to the model during this call.
    ///
    /// Each element must be a valid JSON object conforming to the provider's
    /// tool-schema format (Anthropic `tools` array, `OpenAI` `functions` array,
    /// etc.). Providers that do not yet support tool injection may ignore this
    /// field.
    pub tools: Option<Vec<serde_json::Value>>,
}

/// A single unit of streamed output from a provider.
#[derive(Debug, Clone, PartialEq)]
pub enum Delta {
    /// Incremental text emitted by the model.
    Text(String),
    /// Token-usage statistics emitted at the end of the stream.
    Usage {
        /// Number of tokens in the prompt / input.
        input_tokens: u32,
        /// Number of tokens generated in the response.
        output_tokens: u32,
    },
}
