mod audit;
mod cli;
mod daemon;
mod doctor;
mod eval;
mod formatting;
mod governance;
mod local;
mod loop_cmd;
mod mcp;
mod paths;
mod prices;
mod run;

pub use run::run;
mod sandbox;
mod security;
pub mod service;
mod sessions;
mod skills;
mod tasks;
mod terminal;
mod time_window;
mod timeline;
mod tool_gate;
mod usage;
mod workspace;

use std::path::PathBuf;

use anyhow::{Context as _, Result};
use clap::Parser;
use serde_json::json;
use smedja_ingot::Ingot;
use smedja_plugins::SkillRegistry;
use smedja_rpc::client::Client;

#[cfg(test)]
use crate::audit::build_audit_params;
use crate::cli::*;
use crate::doctor::cmd_doctor;
#[cfg(test)]
use crate::doctor::is_subprocess_runner;
use crate::formatting::{
    format_local_gpu, format_local_models, format_metrics_rows, format_savings_rows,
};
use crate::paths::{default_ingot_path, default_socket_path};
#[cfg(test)]
use crate::sandbox::SandboxStatus;
#[cfg(test)]
use crate::security::{cmd_security_report, cmd_security_sbom, cmd_security_scan};
#[cfg(test)]
use crate::skills::cmd_skill_link_ides;
use crate::time_window::{build_metrics_params, since_to_micros};
use crate::tool_gate::cmd_tool_gate;
#[cfg(test)]
use crate::workspace::cmd_workspace_init;

const AGENTS_TOML_TEMPLATE: &str = r#"# .smedja/agents.toml — workspace agent configuration
# Generated by `smj workspace agents init`
# See docs/configuration.md for the full field reference.

[roles.impl]
runner = "local"
tier   = "local"
model  = "Qwen3-14B"
tools  = ["read_file", "edit_file", "bash"]

[roles.review]
runner = "claude"
tier   = "deep"
tools  = ["read_file", "graph_query"]

[roles.test]
runner = "local"
tier   = "local"
tools  = ["read_file", "bash"]
"#;

/// Resolves the XDG config base directory.
///
/// Priority order:
/// 1. `$XDG_CONFIG_HOME` — if set and non-empty
/// 2. `$HOME/.config` — if `$HOME` is set
/// 3. `.config` — relative fallback (should not occur in practice)
#[allow(clippy::too_many_lines)] // all CLI command arms live in one function per the spec
#[cfg(test)]
mod tests;
