mod audit;
mod cli;
mod daemon;
mod doctor;
mod eval;
mod formatting;
mod governance;
mod paths;
mod security;
pub mod service;
mod sessions;
mod skills;
mod tasks;
mod terminal;
mod time_window;
mod tool_gate;
mod workspace;

use std::path::PathBuf;

use anyhow::{Context as _, Result};
use clap::Parser;
use serde_json::json;
use smedja_ingot::Ingot;
use smedja_plugins::SkillRegistry;
use smedja_rpc::client::Client;

use crate::audit::build_audit_params;
use crate::cli::*;
use crate::daemon::{
    cmd_daemon_start, cmd_daemon_status, connect_or_exit, init_tracing, wait_for_daemon_exit,
};
use crate::doctor::cmd_doctor;
#[cfg(test)]
use crate::doctor::is_subprocess_runner;
use crate::eval::cmd_eval_run;
use crate::formatting::{
    format_local_gpu, format_local_models, format_metrics_rows, format_savings_rows,
};
use crate::governance::find_gov_artifact;
use crate::paths::{default_ingot_path, default_socket_path, xdg_config_dir};
use crate::security::{cmd_security_report, cmd_security_sbom, cmd_security_scan};
use crate::sessions::{cmd_session_list, cmd_session_rollback, cmd_session_show};
use crate::skills::{
    cmd_skill_install, cmd_skill_link_ides, cmd_skill_list, cmd_skill_remove, cmd_skill_sync,
    cmd_skill_update,
};
use crate::tasks::{cmd_task_close, cmd_task_create, cmd_task_list, cmd_task_show};
use crate::terminal::cmd_term_install;
use crate::time_window::{build_metrics_params, since_to_micros};
use crate::tool_gate::cmd_tool_gate;
use crate::workspace::{cmd_workspace_agents, cmd_workspace_init};

const AGENTS_TOML_TEMPLATE: &str = r#"# .smedja/agents.toml — workspace agent configuration
# Generated by `smj workspace agents init`
# See docs/configuration.md for the full field reference.

[roles.impl]
runner = "local"
tier   = "local"
model  = "Qwen3-14B"
tools  = ["read_file", "edit_file", "bash"]

[roles.review]
runner = "claude"
tier   = "deep"
tools  = ["read_file", "graph_query"]

[roles.test]
runner = "local"
tier   = "local"
tools  = ["read_file", "bash"]
"#;

/// Resolves the XDG config base directory.
///
/// Priority order:
/// 1. `$XDG_CONFIG_HOME` — if set and non-empty
/// 2. `$HOME/.config` — if `$HOME` is set
/// 3. `.config` — relative fallback (should not occur in practice)
#[allow(clippy::too_many_lines)] // all CLI command arms live in one function per the spec
pub async fn run() -> Result<()> {
    init_tracing();
    let cli = Cli::parse();
    let sock = cli.sock.unwrap_or_else(default_socket_path);

    match cli.command {
        Cmd::Daemon { action } => match action {
            DaemonCmd::Status => cmd_daemon_status(&sock).await?,
            DaemonCmd::Start => cmd_daemon_start()?,
            DaemonCmd::Stop => {
                let base = std::env::var("XDG_RUNTIME_DIR").unwrap_or_else(|_| "/tmp".into());
                let pid_path = std::path::PathBuf::from(base).join("smdjad.pid");
                let pid = std::fs::read_to_string(&pid_path)
                    .context("smdjad not running (no PID file)")?
                    .trim()
                    .to_owned();
                std::process::Command::new("kill")
                    .args(["-TERM", &pid])
                    .status()
                    .context("kill -TERM failed")?;
                println!("smdjad stopped (pid {pid})");
            }
            DaemonCmd::Restart => {
                let base = std::env::var("XDG_RUNTIME_DIR").unwrap_or_else(|_| "/tmp".into());
                let pid_path = std::path::PathBuf::from(base).join("smdjad.pid");
                if let Ok(pid) = std::fs::read_to_string(&pid_path).map(|s| s.trim().to_owned()) {
                    let _ = std::process::Command::new("kill")
                        .args(["-TERM", &pid])
                        .status();
                    wait_for_daemon_exit(&pid, &sock)
                        .context("old smdjad did not shut down cleanly")?;
                }
                cmd_daemon_start()?;
                println!("smdjad restarted");
            }
        },
        Cmd::Skill { action } => {
            let registry = SkillRegistry::new(SkillRegistry::default_path());
            match action {
                SkillCmd::List => cmd_skill_list(&registry)?,
                SkillCmd::Install { path } => cmd_skill_install(&registry, &path)?,
                SkillCmd::Update { name, path } => cmd_skill_update(&registry, &name, &path)?,
                SkillCmd::Remove { name } => cmd_skill_remove(&registry, &name)?,
                SkillCmd::Sync { path } => cmd_skill_sync(&registry, &path)?,
                SkillCmd::LinkIdes { dir } => {
                    cmd_skill_link_ides(&SkillRegistry::default_path(), &dir)?;
                }
            }
        }
        Cmd::Task { action } => {
            // Export and Import operate on the local Ingot DB directly without
            // needing a running smdjad daemon.
            match action {
                TaskCmd::Export { change } => {
                    let db_path = default_ingot_path();
                    let ingot = Ingot::open(&db_path).with_context(|| {
                        format!("failed to open ingot at {}", db_path.display())
                    })?;
                    let records = ingot
                        .export_jsonl(change.as_deref())
                        .context("export_jsonl failed")?;
                    for rec in &records {
                        println!("{}", serde_json::to_string(rec)?);
                    }
                    return Ok(());
                }
                TaskCmd::Import => {
                    use std::io::BufRead as _;
                    let db_path = default_ingot_path();
                    let ingot = Ingot::open(&db_path).with_context(|| {
                        format!("failed to open ingot at {}", db_path.display())
                    })?;
                    let stdin = std::io::stdin();
                    let mut records: Vec<serde_json::Value> = Vec::new();
                    for line in stdin.lock().lines() {
                        let line = line.context("failed to read stdin")?;
                        let line = line.trim().to_owned();
                        if line.is_empty() {
                            continue;
                        }
                        let val: serde_json::Value =
                            serde_json::from_str(&line).context("invalid JSON line")?;
                        records.push(val);
                    }
                    let n = ingot
                        .import_jsonl(&records)
                        .context("import_jsonl failed")?;
                    println!("Imported {n} record(s)");
                    return Ok(());
                }
                _ => {}
            }

            let mut client = connect_or_exit(&sock).await;
            match action {
                TaskCmd::List { status } => cmd_task_list(&mut client, status.as_deref()).await?,
                TaskCmd::Show { id } => cmd_task_show(&mut client, &id).await?,
                TaskCmd::Create { title, description } => {
                    cmd_task_create(&mut client, &title, description.as_deref()).await?;
                }
                TaskCmd::Close { id } => cmd_task_close(&mut client, &id).await?,
                TaskCmd::Parallel { goal, roles } => {
                    let resp = client
                        .call("task.parallel", json!({ "goal": goal, "roles": roles }))
                        .await
                        .context("task.parallel failed")?;
                    if let Some(tasks) = resp["tasks"].as_array() {
                        for t in tasks {
                            println!(
                                "{} ({})",
                                t["task_id"].as_str().unwrap_or("?"),
                                t["role"].as_str().unwrap_or("?"),
                            );
                        }
                    }
                }
                TaskCmd::Status { id } => {
                    let resp = client
                        .call("task.get", json!({ "id": id }))
                        .await
                        .context("task.get failed")?;
                    println!(
                        "{}",
                        serde_json::to_string_pretty(&resp).unwrap_or_default()
                    );
                }
                TaskCmd::Cancel { id } => {
                    client
                        .call("task.cancel", json!({ "task_id": id }))
                        .await
                        .context("task.cancel failed")?;
                    println!("cancelled: {id}");
                }
                // Already handled above; unreachable but required for exhaustiveness.
                TaskCmd::Export { .. } | TaskCmd::Import => unreachable!(),
            }
        }
        Cmd::Session { action } => {
            if let SessionCmd::Blocks { id } = action {
                eprintln!("smj session blocks: 'session.blocks' RPC not yet implemented");
                eprintln!("  session: {id}");
                std::process::exit(1);
            } else {
                let mut client = connect_or_exit(&sock).await;
                match action {
                    SessionCmd::Start { cowork, task } => {
                        let resp = client
                            .call(
                                "session.create",
                                json!({
                                    "cowork_mode": cowork,
                                    "task_description": task,
                                }),
                            )
                            .await
                            .context("session.create failed")?;
                        let session_id = resp["id"].as_str().unwrap_or("?");
                        println!("Session: {session_id}");
                        if let Some(task_id) = resp["task_id"].as_str() {
                            println!("Task created: {task_id}");
                        }
                    }
                    SessionCmd::List => cmd_session_list(&mut client).await?,
                    SessionCmd::Show { id } => cmd_session_show(&mut client, &id).await?,
                    SessionCmd::Rollback { id, turn } => {
                        cmd_session_rollback(&mut client, &id, turn).await?;
                    }
                    SessionCmd::Fork { id, .. } => {
                        let resp = client
                            .call("session.fork", json!({ "session_id": id }))
                            .await
                            .context("session.fork failed")?;
                        println!(
                            "Forked: {} → {}",
                            id,
                            resp["session_id"].as_str().unwrap_or("?")
                        );
                    }
                    SessionCmd::Checkpoint { id } => {
                        let resp = client
                            .call("session.checkpoint.list", json!({ "session_id": id }))
                            .await
                            .context("session.checkpoint.list failed")?;
                        if let Some(arr) = resp.as_array() {
                            for cp in arr {
                                println!(
                                    "turn={} ts={} messages={}",
                                    cp["turn_n"].as_i64().unwrap_or(-1),
                                    cp["created_at"].as_f64().unwrap_or(0.0),
                                    cp["message_count"].as_u64().unwrap_or(0),
                                );
                            }
                        }
                    }
                    SessionCmd::Blocks { .. } => unreachable!(),
                    SessionCmd::Export { id, format } => {
                        if format == "md" {
                            let resp = client
                                .call(
                                    "session.messages",
                                    json!({ "session_id": id, "limit": 1000 }),
                                )
                                .await
                                .context("session.messages failed")?;
                            let messages = resp["messages"].as_array().cloned().unwrap_or_default();
                            println!("# Session {id}\n");
                            for msg in &messages {
                                let role = msg["role"].as_str().unwrap_or("unknown");
                                let content = msg["content"].as_str().unwrap_or("");
                                match role {
                                    "user" => println!("**User:**\n\n{content}\n"),
                                    "assistant" => println!("**Assistant:**\n\n{content}\n"),
                                    _ => println!("**{role}:**\n\n{content}\n"),
                                }
                            }
                        } else {
                            let resp = client
                                .call("session.export", json!({ "id": id }))
                                .await
                                .context("session.export failed")?;
                            println!("{}", serde_json::to_string_pretty(&resp)?);
                        }
                    }
                    SessionCmd::Compact { id } => {
                        let resp = client
                            .call("session.compact", json!({ "session_id": id }))
                            .await
                            .context("session.compact failed")?;
                        let summary = resp["summary"].as_str().unwrap_or("(no summary)");
                        println!("Compaction summary for {id}:\n{summary}");
                    }
                    SessionCmd::Tokens { id } => {
                        let resp = client
                            .call("session.token_usage", json!({ "session_id": id }))
                            .await
                            .context("session.token_usage failed")?;
                        if let Some(arr) = resp.as_array() {
                            println!(
                                "{:<8} {:<12} {:<12} {:<16} {:<16}",
                                "turn_n", "input_tok", "output_tok", "cum_input", "cum_output"
                            );
                            println!("{}", "-".repeat(68));
                            for snap in arr {
                                println!(
                                    "{:<8} {:<12} {:<12} {:<16} {:<16}",
                                    snap["turn_n"].as_i64().unwrap_or(-1),
                                    snap["input_tok"].as_i64().unwrap_or(0),
                                    snap["output_tok"].as_i64().unwrap_or(0),
                                    snap["cumulative_input"].as_i64().unwrap_or(0),
                                    snap["cumulative_output"].as_i64().unwrap_or(0),
                                );
                            }
                        }
                    }
                }
            }
        }
        Cmd::Cost { session, json, .. } => {
            let mut client = Client::connect(&sock)
                .await
                .with_context(|| format!("smdjad not running ({})", sock.display()))?;
            if let Some(session_id) = session {
                let resp = client
                    .call("session.cost", json!({"session_id": session_id}))
                    .await
                    .context("session.cost failed")?;
                if json {
                    println!("{}", serde_json::to_string_pretty(&resp)?);
                } else {
                    let usd = resp["total_usd"].as_f64().unwrap_or(0.0);
                    println!("SESSION  {session_id}  TOTAL  ${usd:.6}");
                    if let Some(rows) = resp["breakdown"].as_array() {
                        if !rows.is_empty() {
                            println!();
                            println!(
                                "{:<32}  {:<12}  {:>5}  {:>8}  {:>8}  {:>10}",
                                "MODEL", "RUNNER", "TURNS", "INPUT", "OUTPUT", "COST"
                            );
                            println!("{}", "-".repeat(82));
                            for row in rows {
                                let model = row["model"].as_str().unwrap_or("-");
                                let runner = row["runner"].as_str().unwrap_or("-");
                                let turns = row["turns"].as_i64().unwrap_or(0);
                                let input = row["input_tok"].as_i64().unwrap_or(0);
                                let output = row["output_tok"].as_i64().unwrap_or(0);
                                let cost = row["cost_usd"].as_f64().unwrap_or(0.0);
                                println!(
                                    "{model:<32}  {runner:<12}  {turns:>5}  {input:>8}  {output:>8}  ${cost:.6}",
                                );
                            }
                        }
                    }
                }
            } else {
                // All-sessions summary
                let sessions_resp = client
                    .call("session.list", json!({}))
                    .await
                    .context("session.list failed")?;
                let sessions = sessions_resp["sessions"]
                    .as_array()
                    .cloned()
                    .unwrap_or_default();
                if json {
                    let mut all_costs: Vec<serde_json::Value> = Vec::new();
                    for sess in &sessions {
                        let sid = sess["id"].as_str().unwrap_or_default();
                        if let Ok(cost_resp) = client
                            .call("session.cost", json!({"session_id": sid}))
                            .await
                        {
                            all_costs.push(cost_resp);
                        }
                    }
                    println!("{}", serde_json::to_string_pretty(&all_costs)?);
                } else {
                    println!(
                        "{:<32}  {:<12}  {:>5}  {:>8}  {:>8}  {:>10}",
                        "model", "runner", "turns", "in_tok", "out_tok", "cost_usd"
                    );
                    println!("{}", "-".repeat(80));
                    let mut total_cost = 0.0f64;
                    for sess in &sessions {
                        let sid = sess["id"].as_str().unwrap_or_default();
                        if let Ok(cost_resp) = client
                            .call("session.cost", json!({"session_id": sid}))
                            .await
                        {
                            if let Some(rows) = cost_resp["breakdown"].as_array() {
                                for row in rows {
                                    let model = row["model"].as_str().unwrap_or("-");
                                    let runner = row["runner"].as_str().unwrap_or("-");
                                    let turns = row["turns"].as_i64().unwrap_or(0);
                                    let input = row["input_tok"].as_i64().unwrap_or(0);
                                    let output = row["output_tok"].as_i64().unwrap_or(0);
                                    let cost = row["cost_usd"].as_f64().unwrap_or(0.0);
                                    total_cost += cost;
                                    println!(
                                        "{model:<32}  {runner:<12}  {turns:>5}  {input:>8}  {output:>8}  ${cost:.6}",
                                    );
                                }
                            }
                        }
                    }
                    println!("{}", "-".repeat(80));
                    println!("{:<56}  ${total_cost:.6}", "TOTAL");
                }
            }
        }
        Cmd::Metrics {
            tier,
            since,
            until,
            runner,
            json,
        } => {
            let mut client = Client::connect(&sock)
                .await
                .with_context(|| format!("smdjad not running ({})", sock.display()))?;
            let now_micros = chrono::Utc::now().timestamp_micros();
            let since_micros = since_to_micros(&since, now_micros)?;
            let until_micros = match until {
                Some(spec) => Some(since_to_micros(&spec, now_micros)?),
                None => None,
            };
            let params = build_metrics_params(&tier, since_micros, until_micros);
            let resp = client
                .call("metrics.summary", params)
                .await
                .context("metrics.summary failed")?;
            if json {
                println!("{}", serde_json::to_string_pretty(&resp)?);
            } else {
                for line in format_metrics_rows(&resp, runner.as_deref()) {
                    println!("{line}");
                }
            }
        }
        Cmd::Savings {
            tier,
            since,
            until,
            json,
        } => {
            let mut client = Client::connect(&sock)
                .await
                .with_context(|| format!("smdjad not running ({})", sock.display()))?;
            let now_micros = chrono::Utc::now().timestamp_micros();
            let since_micros = since_to_micros(&since, now_micros)?;
            let until_micros = match until {
                Some(spec) => Some(since_to_micros(&spec, now_micros)?),
                None => None,
            };
            let params = build_metrics_params(&tier, since_micros, until_micros);
            let resp = client
                .call("savings.summary", params)
                .await
                .context("savings.summary failed")?;
            if json {
                println!("{}", serde_json::to_string_pretty(&resp)?);
            } else {
                for line in format_savings_rows(&resp) {
                    println!("{line}");
                }
            }
        }
        Cmd::Workspace { action } => match action {
            WorkspaceCmd::Agents {
                action: agents_action,
            } => match agents_action {
                AgentsCmd::Show => {
                    let mut client = Client::connect(&sock)
                        .await
                        .with_context(|| format!("smdjad not running ({})", sock.display()))?;
                    cmd_workspace_agents(&mut client).await?;
                }
                AgentsCmd::Init => {
                    let target = std::path::Path::new(".smedja");
                    std::fs::create_dir_all(target)?;
                    let agents_toml = target.join("agents.toml");
                    if agents_toml.exists() {
                        anyhow::bail!(".smedja/agents.toml already exists");
                    }
                    std::fs::write(&agents_toml, AGENTS_TOML_TEMPLATE)?;
                    println!("Created {}", agents_toml.display());
                }
            },
            WorkspaceCmd::Init { path } => {
                let target = path.unwrap_or_else(|| std::env::current_dir().expect("cwd"));
                if !target.exists() {
                    anyhow::bail!("path does not exist: {}", target.display());
                }
                let mut client = Client::connect(&sock)
                    .await
                    .with_context(|| format!("smdjad not running ({})", sock.display()))?;
                let resp = client
                    .call(
                        "graph.index",
                        json!({ "workspace": target.display().to_string() }),
                    )
                    .await
                    .context("graph.index failed")?;
                let count = resp["indexed"].as_u64().unwrap_or(0);
                println!("Indexed {count} symbols in {}", target.display());
                cmd_workspace_init(&target)?;
            }
            WorkspaceCmd::Index { commit_sha } => {
                // `commit_sha` is accepted for CLI compatibility; the server-side
                // index performs a full re-index.
                let _ = commit_sha;
                let workspace =
                    std::env::current_dir().context("cannot determine current directory")?;
                let mut client = Client::connect(&sock)
                    .await
                    .with_context(|| format!("smdjad not running ({})", sock.display()))?;
                let resp = client
                    .call(
                        "graph.index",
                        json!({ "workspace": workspace.display().to_string() }),
                    )
                    .await
                    .context("graph.index failed")?;
                let count = resp["indexed"].as_u64().unwrap_or(0);
                println!("Indexed {count} symbols in {}", workspace.display());
            }
            WorkspaceCmd::Add { path } => {
                let workspace =
                    std::env::current_dir().context("cannot determine current directory")?;
                let smedja_dir = workspace.join(".smedja");
                std::fs::create_dir_all(&smedja_dir)?;
                let toml_path = smedja_dir.join("workspace.toml");

                // Read existing content or start fresh.
                let mut content = if toml_path.exists() {
                    std::fs::read_to_string(&toml_path).context("failed to read workspace.toml")?
                } else {
                    String::new()
                };

                // Append the new path entry.
                if !content.is_empty() && !content.ends_with('\n') {
                    content.push('\n');
                }
                content.push_str("\n[[workspace.paths]]\npath = \"");
                content.push_str(&path);
                content.push_str("\"\n");
                std::fs::write(&toml_path, &content).context("failed to write workspace.toml")?;
                println!("Added path '{}' to {}", path, toml_path.display());
            }
        },
        Cmd::Audit { action } => match action {
            AuditCmd::Run {
                path,
                branch,
                pr,
                diff,
                report,
                format,
            } => {
                let workspace = std::env::current_dir()
                    .map(|p| p.display().to_string())
                    .ok();
                let params = build_audit_params(
                    path.as_deref(),
                    branch.as_deref(),
                    pr.as_deref(),
                    diff,
                    report.as_deref(),
                    &format,
                    workspace.as_deref(),
                );
                let mut client = Client::connect(&sock)
                    .await
                    .with_context(|| format!("smdjad not running ({})", sock.display()))?;
                let resp = client
                    .call("audit.run", params)
                    .await
                    .context("audit.run failed")?;
                if format == "json" {
                    println!("{}", serde_json::to_string_pretty(&resp)?);
                } else if let Some(report_path) = resp.get("report_path").and_then(|v| v.as_str()) {
                    println!("Report written to {report_path}");
                } else if let Some(body) = resp.get("report").and_then(|v| v.as_str()) {
                    println!("{body}");
                } else {
                    println!("{}", serde_json::to_string_pretty(&resp)?);
                }
            }
            AuditCmd::Query {
                session,
                since,
                action,
            } => {
                let mut client = Client::connect(&sock)
                    .await
                    .with_context(|| format!("smdjad not running ({})", sock.display()))?;
                let mut params = serde_json::json!({});
                if let Some(sid) = session {
                    params["session_id"] = serde_json::Value::String(sid);
                }
                if let Some(s) = since {
                    params["since"] = serde_json::Value::String(s);
                }
                if let Some(a) = action {
                    params["action_type"] = serde_json::Value::String(a);
                }
                let resp = client
                    .call("audit.list", params)
                    .await
                    .context("audit.list failed")?;
                println!("{}", serde_json::to_string_pretty(&resp)?);
            }
            AuditCmd::PromptDiff { change } => {
                let db_path = default_ingot_path();
                let ingot = Ingot::open(&db_path)
                    .with_context(|| format!("failed to open ingot at {}", db_path.display()))?;
                let hashes = ingot
                    .list_prompt_hashes(&change)
                    .context("list_prompt_hashes failed")?;
                if hashes.is_empty() {
                    println!("No prompt hashes recorded for change '{change}'");
                } else {
                    println!("{:<20} {:<64} ts", "role", "hash");
                    println!("{}", "-".repeat(90));
                    for h in &hashes {
                        println!("{:<20} {:<64} {}", h.role, h.hash, h.ts);
                    }
                }
            }
            AuditCmd::Who { session } => {
                let mut client = Client::connect(&sock)
                    .await
                    .with_context(|| format!("smdjad not running ({})", sock.display()))?;
                let resp = client
                    .call("audit.list", json!({ "session_id": session }))
                    .await
                    .context("audit.list failed")?;
                // Group by role_id → action_type → count.
                let mut counts: std::collections::HashMap<
                    String,
                    std::collections::HashMap<String, u64>,
                > = std::collections::HashMap::new();
                if let Some(events) = resp["events"].as_array() {
                    for ev in events {
                        let role_id = ev["role_id"].as_str().unwrap_or("(no role)").to_owned();
                        let action = ev["action_type"].as_str().unwrap_or("?").to_owned();
                        *counts
                            .entry(role_id)
                            .or_default()
                            .entry(action)
                            .or_insert(0) += 1;
                    }
                }
                println!("{:<36} {:<20} count", "role_id", "action_type");
                println!("{}", "-".repeat(64));
                let mut rows: Vec<(String, String, u64)> = counts
                    .into_iter()
                    .flat_map(|(role, actions)| {
                        actions
                            .into_iter()
                            .map(move |(action, count)| (role.clone(), action, count))
                    })
                    .collect();
                rows.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(&b.1)));
                for (role_id, action, count) in &rows {
                    println!("{role_id:<36} {action:<20} {count}");
                }
            }
            AuditCmd::Export {
                change,
                format,
                include_prompts,
            } => {
                let db_path = default_ingot_path();
                let ingot = Ingot::open(&db_path)
                    .with_context(|| format!("failed to open ingot at {}", db_path.display()))?;
                let events = ingot
                    .list_all_audit_events()
                    .context("list_all_audit_events failed")?;
                // Build optional prompt hash lookup: role → hash.
                let prompt_hashes: std::collections::HashMap<String, String> = if include_prompts {
                    ingot
                        .list_prompt_hashes(&change)
                        .unwrap_or_default()
                        .into_iter()
                        .map(|r| (r.role, r.hash))
                        .collect()
                } else {
                    std::collections::HashMap::new()
                };

                match format.as_str() {
                    "csv" => {
                        if include_prompts {
                            println!(
                                "role_id,session_id,tool_name,args_hash,result_tokens,traceparent,ts,prompt_hash"
                            );
                        } else {
                            println!(
                                "role_id,session_id,tool_name,args_hash,result_tokens,traceparent,ts"
                            );
                        }
                        for ev in &events {
                            let role_id = ev.role_id.as_deref().unwrap_or("");
                            let tool = ev.tool_name.as_deref().unwrap_or("");
                            let tp = ev.traceparent.as_deref().unwrap_or("");
                            if include_prompts {
                                let ph = prompt_hashes.get(role_id).map_or("", String::as_str);
                                println!(
                                    "{role_id},{},{tool},,{},{tp},{},{}",
                                    ev.session_id,
                                    ev.output_tok,
                                    ev.ts.as_micros(),
                                    ph
                                );
                            } else {
                                println!(
                                    "{role_id},{},{tool},,{},{tp},{}",
                                    ev.session_id,
                                    ev.output_tok,
                                    ev.ts.as_micros()
                                );
                            }
                        }
                    }
                    _ => {
                        // Default: jsonl
                        for ev in &events {
                            let role_id = ev.role_id.as_deref().unwrap_or("");
                            let mut obj = serde_json::json!({
                                "role_id": role_id,
                                "session_id": ev.session_id,
                                "tool_name": ev.tool_name,
                                "args_hash": "",
                                "result_tokens": ev.output_tok,
                                "traceparent": ev.traceparent,
                                "ts": ev.ts,
                            });
                            if include_prompts {
                                let ph = prompt_hashes.get(role_id).map_or("", String::as_str);
                                obj["prompt_hash"] = serde_json::Value::String(ph.to_owned());
                            }
                            println!("{}", serde_json::to_string(&obj)?);
                        }
                    }
                }
            }
        },
        Cmd::Loop { action } => {
            let mut client = Client::connect(&sock)
                .await
                .with_context(|| format!("smdjad not running ({})", sock.display()))?;
            match action {
                LoopCmd::Run {
                    change,
                    max_slices,
                    follow,
                } => {
                    let resp = client
                        .call(
                            "loop.create",
                            json!({ "change_name": change, "max_slices": max_slices }),
                        )
                        .await
                        .context("loop.create failed")?;
                    let loop_id = resp["loop_id"]
                        .as_str()
                        .ok_or_else(|| anyhow::anyhow!("loop.create returned no loop_id"))?
                        .to_owned();
                    client
                        .call("loop.run", json!({ "loop_id": loop_id }))
                        .await
                        .context("loop.run failed")?;
                    println!("Loop {loop_id} running");
                    if follow {
                        let stream_sock = {
                            let mut p = sock.as_os_str().to_owned();
                            p.push(".stream");
                            std::path::PathBuf::from(p)
                        };
                        follow_loop(&stream_sock, &loop_id)
                            .await
                            .unwrap_or_else(|e| {
                                eprintln!("warning: could not follow loop stream: {e}");
                            });
                    }
                }
                LoopCmd::Status { change } => {
                    let resp = client
                        .call("loop.list", json!({ "change_name": change }))
                        .await
                        .context("loop.list failed")?;
                    println!(
                        "{}",
                        serde_json::to_string_pretty(&resp).unwrap_or_default()
                    );
                }
                LoopCmd::Cancel { change } => {
                    let resp = client
                        .call("loop.list", json!({ "change_name": change }))
                        .await
                        .context("loop.list failed")?;
                    let active = resp["loops"]
                        .as_array()
                        .and_then(|arr| {
                            arr.iter().find(|r| {
                                let status = r["status"].as_str().unwrap_or("");
                                status != "cancelled" && status != "done"
                            })
                        })
                        .and_then(|r| r["id"].as_str())
                        .map(str::to_owned);
                    match active {
                        Some(loop_id) => {
                            client
                                .call("loop.cancel", json!({ "loop_id": loop_id }))
                                .await
                                .context("loop.cancel failed")?;
                            println!("Loop {loop_id} cancelled");
                        }
                        None => {
                            println!("No active loop for change {change}");
                        }
                    }
                }
                LoopCmd::Retire { change } => {
                    // Find the most recent complete or failed loop for this change.
                    let resp = client
                        .call("loop.list", json!({ "change_name": change }))
                        .await
                        .context("loop.list failed")?;
                    let loop_id = resp["loops"]
                        .as_array()
                        .and_then(|arr| {
                            arr.iter().find(|r| {
                                let status = r["status"].as_str().unwrap_or("");
                                status == "complete" || status == "failed"
                            })
                        })
                        .and_then(|r| r["id"].as_str())
                        .map(str::to_owned)
                        .ok_or_else(|| {
                            anyhow::anyhow!(
                                "No complete or failed loop found for change '{change}'"
                            )
                        })?;
                    client
                        .call("loop.retire", json!({ "loop_id": loop_id }))
                        .await
                        .context("loop.retire failed")?;
                    // Export audit events for the change to a JSONL file.
                    let db_path = default_ingot_path();
                    let out_path = format!("{change}.loop-audit.jsonl");
                    if let Ok(ingot) = Ingot::open(&db_path) {
                        if let Ok(events) = ingot.list_all_audit_events() {
                            if let Ok(mut f) = std::fs::File::create(&out_path) {
                                use std::io::Write as _;
                                for ev in &events {
                                    if let Ok(line) = serde_json::to_string(ev) {
                                        let _ = writeln!(f, "{line}");
                                    }
                                }
                            }
                        }
                    }
                    println!("Loop {loop_id} retired");
                    println!("Audit export: {out_path}");
                }
                LoopCmd::List { status } => {
                    let mut params = serde_json::json!({});
                    if let Some(s) = status {
                        params["status"] = serde_json::Value::String(s);
                    }
                    let resp = client
                        .call("loop.list_by_status", params)
                        .await
                        .context("loop.list_by_status failed")?;
                    if let Some(loops) = resp["loops"].as_array() {
                        println!(
                            "{:<36} {:<20} {:<12} {:<16} updated_at",
                            "id", "change_name", "status", "created_at"
                        );
                        println!("{}", "-".repeat(100));
                        for rec in loops {
                            println!(
                                "{:<36} {:<20} {:<12} {:<16} {}",
                                rec["id"].as_str().unwrap_or("?"),
                                rec["change_name"].as_str().unwrap_or("?"),
                                rec["status"].as_str().unwrap_or("?"),
                                rec["created_at"].as_f64().unwrap_or(0.0),
                                rec["updated_at"].as_f64().unwrap_or(0.0),
                            );
                        }
                    }
                }
            }
        }
        Cmd::Sandbox { action } => match action {
            SandboxCmd::Build => {
                println!("Building smedja-sandbox:latest...");
                let status = std::process::Command::new("docker")
                    .args(["build", "-t", "smedja-sandbox:latest", "scripts/sandbox/"])
                    .status()
                    .map_err(|e| anyhow::anyhow!("docker not found: {e}"))?;
                if status.success() {
                    println!("Image built successfully.");
                } else {
                    anyhow::bail!("docker build failed");
                }
            }
            SandboxCmd::Status => {
                let status = SandboxStatus::detect();
                println!("Sandbox backend: {}", status.backend);
                println!(
                    "Available:       {}",
                    if status.available { "yes" } else { "no" }
                );
                println!("Network policy:  {}", status.network_policy);
                println!("Fallback mode:   {}", status.mode);
            }
        },
        Cmd::Mcp { action } => {
            let mut client = Client::connect(&sock)
                .await
                .with_context(|| format!("smdjad not running ({})", sock.display()))?;
            match action {
                McpCmd::Add { name, url, stdio } => {
                    let resp = client
                        .call(
                            "mcp.register",
                            json!({
                                "name": name,
                                "url": url,
                                "transport": if stdio.is_some() { "stdio" } else { "http" },
                                "tools_json": null,
                            }),
                        )
                        .await
                        .context("mcp.register failed")?;
                    println!("registered: {}", resp["name"].as_str().unwrap_or(&name));
                }
                McpCmd::List => {
                    let servers = client
                        .call("mcp.list", json!({}))
                        .await
                        .context("mcp.list failed")?;
                    if let Some(arr) = servers.as_array() {
                        for s in arr {
                            println!(
                                "{} {} ({})",
                                s["name"].as_str().unwrap_or("?"),
                                s["url"].as_str().unwrap_or(""),
                                s["transport"].as_str().unwrap_or("?"),
                            );
                        }
                    }
                }
                McpCmd::Remove { name } => {
                    client
                        .call("mcp.remove", json!({ "name": name }))
                        .await
                        .context("mcp.remove failed")?;
                    println!("removed: {name}");
                }
                McpCmd::Refresh { name } => {
                    let mut params = serde_json::json!({});
                    if let Some(n) = name {
                        params["name"] = serde_json::Value::String(n);
                    }
                    let result: serde_json::Value = client
                        .call("mcp.refresh", params)
                        .await
                        .map_err(|e| anyhow::anyhow!("mcp.refresh failed: {e}"))?;
                    println!(
                        "Refreshed {} server(s)",
                        result
                            .get("refreshed")
                            .and_then(serde_json::Value::as_u64)
                            .unwrap_or(0)
                    );
                }
            }
        }
        Cmd::Prices { action } => match action {
            PricesCmd::Update { file } => {
                if let Some(src) = file {
                    // ponytail: copy file to daemon config dir; daemon reloads on next request
                    let dest = xdg_config_dir().join("smedja").join("prices.toml");
                    std::fs::copy(&src, &dest)?;
                    println!("prices.toml updated \u{2192} {}", dest.display());
                } else {
                    // Print the embedded prices.toml location
                    println!("prices.toml is read from the daemon's config directory at startup");
                }
            }
        },
        Cmd::Timeline { action } => {
            let db_path = default_ingot_path();
            let ingot = Ingot::open(&db_path)
                .with_context(|| format!("failed to open ingot at {}", db_path.display()))?;
            match action {
                TimelineCmd::Conversations { since, json } => {
                    let rollups = ingot.recent_conversations(50)?;
                    let rollups: Vec<_> = if let Some(since_secs) = since {
                        let cutoff = std::time::SystemTime::now()
                            .duration_since(std::time::UNIX_EPOCH)
                            .unwrap_or_default()
                            .as_secs()
                            .saturating_sub(since_secs)
                            .try_into()
                            .unwrap_or(i64::MAX);
                        rollups
                            .into_iter()
                            .filter(|r| r.started_at >= cutoff)
                            .collect()
                    } else {
                        rollups
                    };
                    if json {
                        let arr: Vec<serde_json::Value> = rollups
                            .iter()
                            .map(|r| {
                                serde_json::json!({
                                    "conversation_id": r.conversation_id,
                                    "started_at": r.started_at,
                                    "last_seen_at": r.last_seen_at,
                                    "agent_count": r.agent_count,
                                    "llm_call_count": r.llm_call_count,
                                    "tool_call_count": r.tool_call_count,
                                    "failure_count": r.failure_count,
                                    "input_token_total": r.input_token_total,
                                    "output_token_total": r.output_token_total,
                                })
                            })
                            .collect();
                        println!("{}", serde_json::to_string_pretty(&arr)?);
                    } else if rollups.is_empty() {
                        println!("No conversations found.");
                    } else {
                        println!(
                            "{:<40} {:>8} {:>8} {:>6} {:>6}",
                            "CONVERSATION", "LLM", "TOOLS", "FAIL", "TOKENS"
                        );
                        for r in &rollups {
                            println!(
                                "{:<40} {:>8} {:>8} {:>6} {:>6}",
                                &r.conversation_id[..r.conversation_id.len().min(40)],
                                r.llm_call_count,
                                r.tool_call_count,
                                r.failure_count,
                                r.input_token_total + r.output_token_total,
                            );
                        }
                    }
                }
                TimelineCmd::Show {
                    conversation_id,
                    failures_only,
                    json,
                } => {
                    let events = if failures_only {
                        ingot.failed_events(&conversation_id)?
                    } else {
                        ingot.conversation_timeline(&conversation_id)?
                    };
                    if json {
                        println!("{}", serde_json::to_string_pretty(&events)?);
                    } else if events.is_empty() {
                        println!("No events for conversation {conversation_id}");
                    } else {
                        for ev in &events {
                            println!(
                                "{:.0} {:12} {:8} {:<30} trace:{} span:{}",
                                ev.ts.as_secs_f64(),
                                ev.action_type,
                                ev.status.as_deref().unwrap_or("-"),
                                ev.tool_name.as_deref().unwrap_or(ev.actor.as_str()),
                                ev.trace_id.as_deref().unwrap_or("-"),
                                ev.span_id.as_deref().unwrap_or("-"),
                            );
                        }
                    }
                }
                TimelineCmd::Open { id } => {
                    let template = std::env::var("SMEDJA_TIMELINE_URL").unwrap_or_default();
                    if template.is_empty() {
                        println!("Set SMEDJA_TIMELINE_URL to open traces in a backend.");
                        println!("Example (Honeycomb): SMEDJA_TIMELINE_URL=https://ui.honeycomb.io/your-team/environments/prod/trace?trace_id={{id}}");
                        println!("ID: {id}");
                    } else {
                        let url = template.replace("{id}", &id);
                        println!("{url}");
                    }
                }
            }
        }
        Cmd::Service { action } => service::run(&action)?,
        Cmd::Security { action } => match action {
            SecurityCmd::Scan { path } => {
                let target = path.unwrap_or_else(|| std::env::current_dir().expect("cwd"));
                cmd_security_scan(&target);
            }
            SecurityCmd::Report => {
                let db_path = default_ingot_path();
                let ingot = Ingot::open(&db_path)
                    .with_context(|| format!("failed to open ingot at {}", db_path.display()))?;
                cmd_security_report(&ingot)?;
            }
            SecurityCmd::Sbom { lockfile } => {
                let lock = lockfile.unwrap_or_else(|| PathBuf::from("Cargo.lock"));
                cmd_security_sbom(&lock)?;
            }
        },
        Cmd::Term { action } => match action {
            TermCmd::Install { bin_path, prefix } => {
                let prefix = prefix.unwrap_or_else(|| {
                    std::env::var("HOME").map_or_else(
                        |_| PathBuf::from(".local/bin"),
                        |h| PathBuf::from(h).join(".local/bin"),
                    )
                });
                let url = bin_path.unwrap_or_else(|| {
                    let os = std::env::consts::OS;
                    if os == "macos" {
                        "https://github.com/mwigge/smedja/releases/latest/download/smedja-darwin-x86_64.tar.gz".to_owned()
                    } else {
                        "https://github.com/mwigge/smedja/releases/latest/download/smedja-linux-x86_64.tar.gz".to_owned()
                    }
                });
                let prefix_clone = prefix.clone();
                let url_clone = url.clone();
                tokio::task::spawn_blocking(move || cmd_term_install(&url_clone, &prefix_clone))
                    .await
                    .context("install task panicked")??;
            }
            TermCmd::ConvertWezterm => {
                eprintln!("smj term convert-wezterm: not yet implemented");
                std::process::exit(1);
            }
        },
        Cmd::Eval { action } => match action {
            EvalCmd::Run {
                suite,
                online,
                json,
                threshold,
            } => cmd_eval_run(&suite, online, json, threshold)?,
        },
        Cmd::Gov { action } => {
            let ws = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
            match action {
                GovCmd::List { kind } => {
                    let gov_dir = ws.join("gov");
                    let dirs: Vec<&str> = match kind.as_deref() {
                        Some("wi") => vec!["work-items"],
                        Some("rfc") => vec!["rfcs"],
                        Some("adr") => vec!["adrs"],
                        _ => vec!["work-items", "rfcs", "adrs"],
                    };
                    for dir_name in dirs {
                        let dir = gov_dir.join(dir_name);
                        if !dir.exists() {
                            continue;
                        }
                        let mut entries: Vec<_> = std::fs::read_dir(&dir)
                            .into_iter()
                            .flatten()
                            .flatten()
                            .filter(|e| e.path().extension().is_some_and(|x| x == "toml"))
                            .collect();
                        entries.sort_by_key(std::fs::DirEntry::file_name);
                        for entry in entries {
                            let path = entry.path();
                            let text = std::fs::read_to_string(&path).unwrap_or_default();
                            let id = path
                                .file_stem()
                                .map(|s| s.to_string_lossy().to_string())
                                .unwrap_or_default();
                            let title = text
                                .lines()
                                .find(|l| l.starts_with("title"))
                                .and_then(|l| l.split_once('=').map(|x| x.1))
                                .map(|s| s.trim().trim_matches('"').to_owned())
                                .unwrap_or_default();
                            let status = text
                                .lines()
                                .find(|l| l.starts_with("status"))
                                .and_then(|l| l.split_once('=').map(|x| x.1))
                                .map(|s| s.trim().trim_matches('"').to_owned())
                                .unwrap_or_default();
                            println!("{id:<12}  {status:<14}  {title}");
                        }
                    }
                }
                GovCmd::Transition { id, status } => {
                    const VALID: &[&str] = &["planned", "in_progress", "done", "cancelled"];
                    if !VALID.contains(&status.as_str()) {
                        eprintln!(
                            "error: invalid status '{status}'. Valid: planned | in_progress | done | cancelled"
                        );
                        std::process::exit(1);
                    }
                    let gov_dir = ws.join("gov");
                    let id_upper = id.to_uppercase();
                    let found = find_gov_artifact(&gov_dir, &id_upper);
                    if let Some(path) = found {
                        let text = std::fs::read_to_string(&path)?;
                        let updated = text
                            .lines()
                            .map(|l| {
                                if l.trim_start().starts_with("status") {
                                    format!("status = \"{status}\"")
                                } else {
                                    l.to_owned()
                                }
                            })
                            .collect::<Vec<_>>()
                            .join("\n");
                        std::fs::write(&path, updated)?;
                        println!("{id_upper}: status \u{2192} {status}");
                    } else {
                        eprintln!("error: artifact '{id}' not found in gov/");
                        std::process::exit(1);
                    }
                }
                GovCmd::Create { title, description } => {
                    let wi_dir = ws.join("gov").join("work-items");
                    std::fs::create_dir_all(&wi_dir)?;
                    #[allow(clippy::cast_possible_truncation)]
                    let next_n: u32 = std::fs::read_dir(&wi_dir)
                        .into_iter()
                        .flatten()
                        .flatten()
                        .filter(|e| e.path().extension().is_some_and(|x| x == "toml"))
                        .count() as u32
                        + 1;
                    let id = format!("WI-{next_n:03}");
                    let desc = description.as_deref().unwrap_or("");
                    let toml = format!(
                        "id = \"{id}\"\ntitle = \"{title}\"\nstatus = \"planned\"\ndescription = \"{desc}\"\ncreated = \"{}\"\n",
                        chrono::Utc::now().format("%Y-%m-%d")
                    );
                    let path = wi_dir.join(format!("{}.toml", id.to_lowercase()));
                    std::fs::write(&path, toml)?;
                    println!("Created {id}: {title}");
                }
            }
        }
        Cmd::Doctor { json } => cmd_doctor(&sock, json).await?,
        Cmd::ToolGate => cmd_tool_gate(&sock).await,
        Cmd::Local { action } => {
            let mut client = Client::connect(&sock)
                .await
                .with_context(|| format!("smdjad not running ({})", sock.display()))?;
            match action {
                LocalCmd::List { json } => {
                    let resp = client
                        .call("local.models", json!({}))
                        .await
                        .context("local.models failed")?;
                    if json {
                        println!("{}", serde_json::to_string_pretty(&resp)?);
                    } else {
                        for line in format_local_models(&resp) {
                            println!("{line}");
                        }
                    }
                }
                LocalCmd::Gpu { json } => {
                    let resp = client
                        .call("local.gpu", json!({}))
                        .await
                        .context("local.gpu failed")?;
                    if json {
                        println!("{}", serde_json::to_string_pretty(&resp)?);
                    } else {
                        println!("{}", format_local_gpu(&resp));
                    }
                }
                LocalCmd::Swap { model } => {
                    let resp = client
                        .call("local.swap", json!({ "model": model }))
                        .await
                        .context("local.swap failed")?;
                    let active = resp["active_model_id"].as_str().unwrap_or(&model);
                    let latency = resp["swap_latency_ms"].as_u64().unwrap_or(0);
                    let explicit = resp["explicit_swap"].as_bool().unwrap_or(false);
                    let path = if explicit {
                        "explicit swap"
                    } else {
                        "label fallback"
                    };
                    println!("swapped to {active} via {path} ({latency} ms)");
                }
                LocalCmd::Install { model } => {
                    let resp = client
                        .call("local.install", json!({ "model": model }))
                        .await
                        .context("local.install failed")?;
                    let installed = resp["installed"].as_bool().unwrap_or(false);
                    if installed {
                        println!("installed {model} (verified in inventory)");
                    } else {
                        let installer_ok = resp["installer_ok"].as_bool().unwrap_or(false);
                        let present = resp["present_in_inventory"].as_bool().unwrap_or(false);
                        println!(
                            "install of {model} not verified \
                             (installer_ok={installer_ok}, present_in_inventory={present})"
                        );
                    }
                }
            }
        }
    }
    Ok(())
}

/// Renders the `local.models` response as a fixed-width table with fit annotations.
///
/// Returns a header row followed by one row per model (id, est VRAM, fit, active
/// marker), or a single notice line when the inventory is empty.
/// Renders the `local.gpu` response as a single human-readable line.
/// Loads a suite, runs it through the eval engine, prints a human report
/// (and the JSON summary when `--json` is set), emits `OTel` metrics, and exits
/// non-zero when the pass rate is below the (possibly overridden) threshold.
///
/// Routing cases are scored deterministically against `Assayer::default_rules`.
/// Agent cases are graded only when `--online` is set; the real loop driver and
/// LLM judge are wired at the daemon boundary, so this operator path supplies
/// an unwired driver/judge that surfaces a clear failure if an online agent
/// case is run without that wiring.
/// Prints the resolved role→runner→tier→model routing table for the current
/// workspace, sourcing each decision from the daemon's `agent.routing` RPC.
///
/// The printed format is identical to the previous in-process implementation so
/// downstream tooling and operators see no change.
/// Returns `true` when `runner_name` uses a subprocess CLI binary rather than
/// the native HTTP API.
/// Prints the provider pool status — which runners are active, whether they
/// use native HTTP or a subprocess CLI binary, and which env vars are set.
/// When `--json` is passed, emits a machine-readable JSON object instead.
/// Initialises tracing, honouring `SMEDJA_LOG_FORMAT`.
///
/// Accepts `text` (default) or `json`. Any unrecognised value falls back to
/// `text` and logs a warning once the subscriber is installed.
/// Returns `true` if a process with the given PID is still alive.
///
/// Uses `kill -0`, which sends no signal but reports whether the PID exists
/// and is signal-able by the caller.
/// Connects to the smdjad socket, printing a targeted diagnostic and exiting
/// with code 1 on failure.
///
/// Distinguishes:
/// - `NotFound` → daemon not started (socket file absent)
/// - `PermissionDenied` → socket exists but caller lacks access
/// - Other I/O errors → generic message
/// Polls until the old daemon has exited and released its socket path.
///
/// Bounded to roughly five seconds; returns an error if the process is still
/// alive or the socket still exists after the deadline so the caller does not
/// race a fresh daemon against the dying one.
/// Returns the path to the smdjad log file, creating its parent directory.
///
/// Resolves to `$XDG_STATE_HOME/smedja/smdjad.log`, falling back to
/// `$HOME/.local/state/smedja/smdjad.log`.
/// Searches `gov/work-items`, `gov/rfcs`, and `gov/adrs` for a TOML file whose
/// stem matches `id` (case-insensitively, compared in uppercase).
/// Connects to the smdjad stream socket and prints NDJSON events for `loop_id`
/// until a terminal state (`done`, `error`, `policy_tampered`) is received or
/// the connection is closed.
async fn follow_loop(stream_sock: &std::path::Path, loop_id: &str) -> anyhow::Result<()> {
    use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
    use tokio::net::UnixStream;

    let mut stream = UnixStream::connect(stream_sock)
        .await
        .context("cannot connect to stream socket")?;
    let req = format!("{{\"task_id\":\"{loop_id}\"}}\n");
    stream.write_all(req.as_bytes()).await?;
    let mut reader = BufReader::new(stream);
    let mut line = String::new();
    loop {
        line.clear();
        let n = reader.read_line(&mut line).await?;
        if n == 0 {
            break;
        }
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        println!("{trimmed}");
        if trimmed.contains(r#""type":"done""#)
            || trimmed.contains(r#""type":"error""#)
            || trimmed.contains(r#""type":"policy_tampered""#)
        {
            break;
        }
    }
    Ok(())
}

/// Initialises a smedja workspace at the given directory.
///
/// Creates `.smedja/` and writes a `workspace.toml` with `auto_index = true`
/// and the current timestamp. Symbol indexing is performed separately via the
/// daemon's `graph.index` RPC by the caller.
/// Runs a workspace posture scan and prints the advisory findings.
///
/// The scan is advisory: it reports findings but blocks nothing. A clean
/// workspace prints a short confirmation.
/// Summarises recorded `security_finding` audit events as a read-only query.
/// Emits a CycloneDX-style SBOM for `lockfile` to stdout.
/// Builds the `audit.run` RPC params from the parsed `smj audit run` flags.
///
/// Scope precedence mirrors the daemon's `resolve_scope`: `--pr` → `--branch` →
/// `--diff`/no-path → a positional `<path>`.
/// Parses a duration string (`7d`, `24h`, `30m`, `90s`, or bare seconds) into a
/// micros-since-epoch lower bound relative to `now_micros`.
///
/// A bare integer is interpreted as seconds. The result is `now_micros` minus
/// the parsed span, clamped at zero.
///
/// # Errors
///
/// Returns an error when the string is not a recognised duration.
/// Parses a duration string into a span in microseconds.
///
/// Accepts a trailing unit suffix `d`/`h`/`m`/`s`; a bare integer is seconds.
/// Builds the `metrics.summary` request params from CLI flags.
///
/// `until` is omitted from the params when `None`, letting the daemon default it
/// to the current time.
/// Renders the `metrics.summary` response into table rows, one per bucket,
/// optionally filtered to a single `runner`.
///
/// Returns the header line followed by one formatted line per bucket. The cost
/// column is the USD `f64` the daemon already converted at its display boundary.
/// Formats a micros-since-epoch bucket start as a UTC `YYYY-MM-DD HH:MM` label.
/// Renders the `savings.summary` response into report lines.
///
/// Leads with the efficiency-ratio headline and the compression / cache totals
/// kept as separate figures (cache savings are "input not re-paid" and are never
/// folded into the compression total), then lists one row per `(bucket, source)`.
/// Resolves a path to its SKILL.md content and the skill name from frontmatter.
#[cfg(test)]
mod tests {
    use super::*;

    // --- smj metrics ---

    #[test]
    fn metrics_parses_subcommand_with_flags() {
        let cli = Cli::try_parse_from([
            "smj", "metrics", "--tier", "hourly", "--since", "24h", "--runner", "claude", "--json",
        ])
        .expect("metrics must parse");
        match cli.command {
            Cmd::Metrics {
                tier,
                since,
                until,
                runner,
                json,
            } => {
                assert_eq!(tier, "hourly");
                assert_eq!(since, "24h");
                assert_eq!(until, None);
                assert_eq!(runner.as_deref(), Some("claude"));
                assert!(json);
            }
            _ => panic!("expected Cmd::Metrics"),
        }
    }

    // --- smj savings ---

    #[test]
    fn savings_parses_subcommand_with_flags() {
        let cli = Cli::try_parse_from([
            "smj", "savings", "--tier", "weekly", "--since", "30d", "--json",
        ])
        .expect("savings must parse");
        match cli.command {
            Cmd::Savings {
                tier,
                since,
                until,
                json,
            } => {
                assert_eq!(tier, "weekly");
                assert_eq!(since, "30d");
                assert_eq!(until, None);
                assert!(json);
            }
            _ => panic!("expected Cmd::Savings"),
        }
    }

    #[test]
    fn savings_tier_defaults_to_daily() {
        let cli = Cli::try_parse_from(["smj", "savings"]).expect("savings must parse");
        match cli.command {
            Cmd::Savings { tier, since, .. } => {
                assert_eq!(tier, "daily");
                assert_eq!(since, "7d");
            }
            _ => panic!("expected Cmd::Savings"),
        }
    }

    #[test]
    fn format_savings_rows_keeps_cache_separate_from_compression() {
        let resp = json!({
            "tier": "daily",
            "compression_saved": 150,
            "cache_saved": 9000,
            "efficiency_ratio": 0.2,
            "buckets": [
                { "bucket_start": 1_767_225_600_000_000_i64, "source": "cache", "tokens_saved": 9000 },
                { "bucket_start": 1_767_225_600_000_000_i64, "source": "filter", "tokens_saved": 150 },
            ],
        });
        let lines = format_savings_rows(&resp);
        let joined = lines.join("\n");
        assert!(
            joined.contains("EFFICIENCY  20.0%"),
            "headline ratio: {joined}"
        );
        assert!(
            joined.contains("COMPRESSION 150 tok"),
            "compression total: {joined}"
        );
        assert!(
            joined.contains("CACHE       9000 tok"),
            "cache total: {joined}"
        );
        // The compression and cache totals are never summed into one figure.
        assert!(
            !joined.contains("9150"),
            "must not fold cache into compression"
        );
        assert!(joined.contains("cache"));
        assert!(joined.contains("filter"));
    }

    #[test]
    fn metrics_tier_defaults_to_daily() {
        let cli = Cli::try_parse_from(["smj", "metrics"]).expect("metrics must parse");
        match cli.command {
            Cmd::Metrics { tier, since, .. } => {
                assert_eq!(tier, "daily");
                assert_eq!(since, "7d");
            }
            _ => panic!("expected Cmd::Metrics"),
        }
    }

    #[test]
    fn since_to_micros_subtracts_duration() {
        // now = 1_000_000s in micros; 1d back = 86_400s earlier.
        let now = 1_000_000_000_000;
        assert_eq!(since_to_micros("1d", now).unwrap(), now - 86_400_000_000);
        assert_eq!(since_to_micros("2h", now).unwrap(), now - 7_200_000_000);
        assert_eq!(since_to_micros("30m", now).unwrap(), now - 1_800_000_000);
        assert_eq!(since_to_micros("45s", now).unwrap(), now - 45_000_000);
        // Bare integer is seconds.
        assert_eq!(since_to_micros("10", now).unwrap(), now - 10_000_000);
    }

    #[test]
    fn since_to_micros_clamps_at_zero() {
        assert_eq!(since_to_micros("100d", 0).unwrap(), 0);
    }

    #[test]
    fn since_to_micros_rejects_garbage() {
        assert!(since_to_micros("notaduration", 0).is_err());
    }

    #[test]
    fn build_metrics_params_omits_until_when_absent() {
        let p = build_metrics_params("daily", 123, None);
        assert_eq!(p["tier"], "daily");
        assert_eq!(p["since"], 123);
        assert!(p.get("until").is_none());
        let p2 = build_metrics_params("hourly", 1, Some(999));
        assert_eq!(p2["until"], 999);
    }

    #[test]
    fn format_metrics_rows_renders_known_response() {
        // 2026-01-01 00:00:00 UTC = 1_767_225_600_000_000 micros.
        let resp = json!({
            "tier": "daily",
            "buckets": [
                {
                    "bucket_start": 1_767_225_600_000_000_i64,
                    "runner": "claude",
                    "turns": 3,
                    "input_tok": 600,
                    "output_tok": 180,
                    "cost_usd": 0.06,
                    "error_count": 1
                },
                {
                    "bucket_start": 1_767_225_600_000_000_i64,
                    "runner": "local",
                    "turns": 1,
                    "input_tok": 400,
                    "output_tok": 80,
                    "cost_usd": 0.0,
                    "error_count": 0
                }
            ]
        });
        let rows = format_metrics_rows(&resp, None);
        assert_eq!(rows.len(), 3, "header + two buckets");
        assert!(rows[0].contains("BUCKET") && rows[0].contains("ERRORS"));
        assert!(rows[1].contains("2026-01-01 00:00"));
        assert!(rows[1].contains("claude"));
        assert!(rows[1].contains("$  0.060000"));
        assert!(rows[2].contains("local"));

        // Runner filter keeps only the matching bucket.
        let filtered = format_metrics_rows(&resp, Some("claude"));
        assert_eq!(filtered.len(), 2, "header + claude only");
        assert!(filtered[1].contains("claude"));
    }

    // --- smj local ---

    #[test]
    fn local_list_parses_subcommand() {
        let cli = Cli::try_parse_from(["smj", "local", "list"]).expect("local list must parse");
        match cli.command {
            Cmd::Local {
                action: LocalCmd::List { json },
            } => assert!(!json, "json defaults off"),
            _ => panic!("expected Cmd::Local List"),
        }
    }

    #[test]
    fn local_swap_parses_model_arg() {
        let cli = Cli::try_parse_from(["smj", "local", "swap", "qwen3-14b"])
            .expect("local swap must parse");
        match cli.command {
            Cmd::Local {
                action: LocalCmd::Swap { model },
            } => assert_eq!(model, "qwen3-14b"),
            _ => panic!("expected Cmd::Local Swap"),
        }
    }

    #[test]
    fn local_install_parses_model_arg() {
        let cli = Cli::try_parse_from(["smj", "local", "install", "llama3-8b"])
            .expect("local install must parse");
        match cli.command {
            Cmd::Local {
                action: LocalCmd::Install { model },
            } => assert_eq!(model, "llama3-8b"),
            _ => panic!("expected Cmd::Local Install"),
        }
    }

    #[test]
    fn format_local_models_renders_inventory_with_fit() {
        let resp = json!({
            "active_model_id": "qwen3-14b",
            "models": [
                { "id": "qwen3-14b", "est_vram_mb": 9000, "fit": "fits", "active": true },
                { "id": "huge-70b", "est_vram_mb": 48000, "fit": "exceeds", "active": false },
                { "id": "no-meta", "est_vram_mb": null, "fit": "unknown", "active": false }
            ]
        });
        let lines = format_local_models(&resp);
        assert_eq!(lines.len(), 4, "header + three models");
        assert!(lines[0].contains("MODEL") && lines[0].contains("FIT"));
        assert!(lines[1].contains("qwen3-14b") && lines[1].contains("fits"));
        assert!(lines[1].contains('*'), "active model must be marked");
        assert!(lines[2].contains("exceeds"));
        assert!(lines[3].contains("unknown") && lines[3].contains('-'));
    }

    #[test]
    fn format_local_models_empty_inventory_notice() {
        let resp = json!({ "models": [] });
        let lines = format_local_models(&resp);
        assert_eq!(lines, vec!["no local models".to_owned()]);
    }

    #[test]
    fn format_local_gpu_renders_detected_and_absent() {
        let detected = json!({
            "device": "RTX 4090", "vram_total_mb": 24000, "vram_free_mb": 20000, "detected": true
        });
        let line = format_local_gpu(&detected);
        assert!(line.contains("RTX 4090") && line.contains("20000/24000"));

        let absent = json!({ "device": null, "detected": false });
        assert_eq!(format_local_gpu(&absent), "no GPU detected");
    }

    // --- smj sandbox status ---

    #[test]
    fn sandbox_status_parses_subcommand() {
        let cli =
            Cli::try_parse_from(["smj", "sandbox", "status"]).expect("sandbox status must parse");
        assert!(matches!(
            cli.command,
            Cmd::Sandbox {
                action: SandboxCmd::Status
            }
        ));
    }

    #[test]
    fn sandbox_status_reports_backend_and_policy() {
        // Mode parsing covers the fallback-mode column.
        assert_eq!(SandboxStatus::mode_from_value("required"), "required");
        assert_eq!(SandboxStatus::mode_from_value("off"), "off");
        assert_eq!(SandboxStatus::mode_from_value(""), "auto");
        assert_eq!(SandboxStatus::mode_from_value("nonsense"), "auto");

        // Network policy parsing covers the network-policy column.
        assert_eq!(SandboxStatus::network_from_value("allowlist"), "allowlist");
        assert_eq!(SandboxStatus::network_from_value("open"), "open");
        assert_eq!(SandboxStatus::network_from_value(""), "none");

        // The resolved status reports a backend name, an availability flag, the
        // network policy, and the fallback mode for the current host.
        let status = SandboxStatus::detect();
        assert!(
            matches!(status.backend, "docker" | "seatbelt" | "landlock" | "none"),
            "backend must be one of the known names; got {}",
            status.backend
        );
        assert!(matches!(status.mode, "auto" | "required" | "off"));
        assert!(matches!(
            status.network_policy,
            "none" | "allowlist" | "open"
        ));
        // `available` is a bool by construction; assert it is consistent with
        // the "none" backend never being available.
        if status.backend == "none" {
            assert!(!status.available);
        }
    }

    // --- smj audit run parsing + params ---

    #[test]
    fn audit_run_parses_path_branch_pr_diff_report_format() {
        let cli = Cli::try_parse_from([
            "smj",
            "audit",
            "run",
            "src/lib.rs",
            "--report",
            "out.md",
            "--format",
            "json",
        ])
        .expect("audit run with a path must parse");
        let Cmd::Audit {
            action:
                AuditCmd::Run {
                    path,
                    branch,
                    pr,
                    diff,
                    report,
                    format,
                },
        } = cli.command
        else {
            panic!("expected an audit run command");
        };
        assert_eq!(path.as_deref(), Some("src/lib.rs"));
        assert_eq!(branch, None);
        assert_eq!(pr, None);
        assert!(!diff);
        assert_eq!(report.as_deref(), Some("out.md"));
        assert_eq!(format, "json");
    }

    #[test]
    fn audit_run_parses_branch_and_pr_flags() {
        let branch = Cli::try_parse_from(["smj", "audit", "run", "--branch", "main"]).unwrap();
        assert!(matches!(
            branch.command,
            Cmd::Audit {
                action: AuditCmd::Run { branch: Some(b), .. }
            } if b == "main"
        ));
        let pr = Cli::try_parse_from(["smj", "audit", "run", "--pr", "42"]).unwrap();
        assert!(matches!(
            pr.command,
            Cmd::Audit {
                action: AuditCmd::Run { pr: Some(p), .. }
            } if p == "42"
        ));
    }

    #[test]
    fn build_audit_params_respects_scope_precedence() {
        // pr wins over branch/path
        let params = build_audit_params(
            Some("src"),
            Some("main"),
            Some("7"),
            false,
            None,
            "md",
            None,
        );
        assert_eq!(params["pr"], "7");
        assert!(params.get("branch").is_none());
        assert!(params.get("path").is_none());

        // path scope with report + workspace
        let params = build_audit_params(
            Some("src"),
            None,
            None,
            false,
            Some("r.md"),
            "json",
            Some("/ws"),
        );
        assert_eq!(params["path"], "src");
        assert_eq!(params["report"], "r.md");
        assert_eq!(params["format"], "json");
        assert_eq!(params["workspace"], "/ws");

        // diff flag overrides a path
        let params = build_audit_params(Some("src"), None, None, true, None, "md", None);
        assert_eq!(params["diff"], true);
        assert!(params.get("path").is_none());
    }

    #[test]
    fn workspace_init_creates_dir_and_toml() {
        let dir = tempfile::tempdir().unwrap();
        cmd_workspace_init(dir.path()).unwrap();
        assert!(dir.path().join(".smedja").exists());
        let toml_content =
            std::fs::read_to_string(dir.path().join(".smedja").join("workspace.toml")).unwrap();
        assert!(toml_content.contains("auto_index = true"));
        assert!(toml_content.contains("last_indexed_at"));
    }

    #[test]
    fn auto_index_fires_when_stale() {
        let dir = tempfile::tempdir().unwrap();
        let smedja_dir = dir.path().join(".smedja");
        std::fs::create_dir_all(&smedja_dir).unwrap();
        let old_ts = (chrono::Utc::now() - chrono::Duration::hours(25)).to_rfc3339();
        let content = format!("[graph]\nauto_index = true\nlast_indexed_at = \"{old_ts}\"\n");
        std::fs::write(smedja_dir.join("workspace.toml"), &content).unwrap();
        // Verify the staleness-check logic matches what smdjad does at session.create.
        let parsed: toml::Value = toml::from_str(&content).unwrap();
        let ts_str = parsed["graph"]["last_indexed_at"].as_str().unwrap();
        let ts = chrono::DateTime::parse_from_rfc3339(ts_str).unwrap();
        let age = chrono::Utc::now().signed_duration_since(ts.with_timezone(&chrono::Utc));
        assert!(age.num_hours() >= 24, "25h old timestamp must be stale");
    }

    #[test]
    fn security_sbom_writes_cyclonedx_document() {
        let dir = tempfile::tempdir().unwrap();
        let lock = dir.path().join("Cargo.lock");
        std::fs::write(
            &lock,
            "version = 3\n\n[[package]]\nname = \"demo\"\nversion = \"1.0.0\"\n",
        )
        .unwrap();
        // Exercise the same path the CLI handler uses.
        let sbom = smedja_security::Sbom::from_lockfile(&lock).unwrap();
        let json = sbom.to_json().unwrap();
        assert!(json.contains("\"bomFormat\": \"CycloneDX\""));
        assert!(json.contains("pkg:cargo/demo@1.0.0"));
        // The handler itself returns Ok on a valid lockfile.
        super::cmd_security_sbom(&lock).unwrap();
    }

    #[test]
    fn security_report_runs_as_read_only_query() {
        let ingot = smedja_ingot::Ingot::open_in_memory().unwrap();
        // No findings recorded → the read-only query still succeeds.
        super::cmd_security_report(&ingot).unwrap();
    }

    #[test]
    fn security_scan_reports_findings_without_blocking() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(".npmrc"), "//r/:_authToken=x").unwrap();
        // Scan runs regardless of findings (advisory; never blocks).
        super::cmd_security_scan(dir.path());
        let findings = smedja_security::scan_posture(dir.path());
        assert!(findings.iter().any(|f| f.rule_id == "flagged-path"));
    }

    #[test]
    fn doctor_subcommand_parses() {
        Cli::try_parse_from(["smj", "doctor"]).expect("smj doctor must parse");
        // --json flag
        Cli::try_parse_from(["smj", "doctor", "--json"]).expect("smj doctor --json must parse");
    }

    #[test]
    fn is_subprocess_runner_distinguishes_native_from_cli() {
        assert!(is_subprocess_runner("claude-cli"));
        assert!(is_subprocess_runner("codex-cli"));
        assert!(!is_subprocess_runner("anthropic"));
        assert!(!is_subprocess_runner("openai"));
        assert!(!is_subprocess_runner("copilot"));
        assert!(!is_subprocess_runner("minimax"));
        assert!(!is_subprocess_runner("berget"));
        assert!(!is_subprocess_runner("local"));
    }

    #[test]
    fn graph_symbols_injected_into_context() {
        // Mirrors the noun-extraction filter used by smdjad's graph auto-injection.
        let message = "implement WorkingMemory seal_prefix function";
        let stop_words = [
            "the", "and", "for", "with", "this", "that", "from", "into", "use", "are", "was",
            "has", "not", "can", "its", "will",
        ];
        let nouns: Vec<&str> = message
            .split_whitespace()
            .filter(|t| t.len() >= 3 && !stop_words.contains(&t.to_lowercase().as_str()))
            .take(5)
            .collect();
        assert!(!nouns.is_empty(), "nouns must be extracted from message");
        assert!(
            nouns.contains(&"implement")
                || nouns.contains(&"WorkingMemory")
                || nouns.contains(&"seal_prefix"),
        );
    }

    #[test]
    fn link_ides_creates_codex_and_cursor_symlinks() {
        let tmp = tempfile::tempdir().expect("tmp");
        let skills_src = tmp.path().join("skills");
        std::fs::create_dir_all(&skills_src).unwrap();
        let project = tmp.path().join("project");
        std::fs::create_dir_all(&project).unwrap();

        cmd_skill_link_ides(&skills_src, &project).expect("link_ides");

        let codex_link = project.join(".codex").join("skills");
        let cursor_link = project.join(".cursor").join("skills");
        assert!(codex_link.is_symlink(), ".codex/skills must be a symlink");
        assert!(cursor_link.is_symlink(), ".cursor/skills must be a symlink");
        assert_eq!(std::fs::read_link(&codex_link).unwrap(), skills_src);
        assert_eq!(std::fs::read_link(&cursor_link).unwrap(), skills_src);
    }

    #[test]
    fn link_ides_skips_existing_correct_symlinks() {
        let tmp = tempfile::tempdir().expect("tmp");
        let skills_src = tmp.path().join("skills");
        std::fs::create_dir_all(&skills_src).unwrap();
        let project = tmp.path().join("project");
        std::fs::create_dir_all(&project).unwrap();

        // Create first time.
        cmd_skill_link_ides(&skills_src, &project).expect("first");
        // Second call must not error.
        cmd_skill_link_ides(&skills_src, &project).expect("second");

        let codex_link = project.join(".codex").join("skills");
        assert_eq!(std::fs::read_link(&codex_link).unwrap(), skills_src);
    }
}
