use std::sync::Arc;

use crate::dispatcher::Dispatcher;
use crate::event::{CorrelationCtx, TurnEvent};
use opentelemetry::trace::TraceContextExt as _;

/// Extracts `(trace_id, span_id)` strings from the currently active `OTel` span.
///
/// Returns `(None, None)` when no valid span is active (e.g. in tests without
/// an `OTel` pipeline installed).
fn current_span_ids() -> (Option<String>, Option<String>) {
    let cx = opentelemetry::Context::current();
    let sc = cx.span().span_context().clone();
    if sc.is_valid() {
        (
            Some(format!("{}", sc.trace_id())),
            Some(format!("{}", sc.span_id())),
        )
    } else {
        (None, None)
    }
}

/// A handle to an in-progress agent turn.
///
/// Creating a `TurnHandle` via [`start`](TurnHandle::start) immediately
/// publishes a [`TurnEvent::Started`] event.  The handle exposes methods for
/// recording mid-turn activity ([`tool_called`](TurnHandle::tool_called),
/// [`delta`](TurnHandle::delta)) and for resolving the turn by consuming the
/// handle ([`complete`](TurnHandle::complete), [`fail`](TurnHandle::fail)).
///
/// The `trace_id` and `span_id` correlation fields are populated from the
/// active OpenTelemetry span at construction time and threaded through all
/// subsequent events emitted by this handle.
pub struct TurnHandle {
    session_id: String,
    turn_id: String,
    dispatcher: Arc<Dispatcher>,
    trace_id: Option<String>,
    span_id: Option<String>,
}

impl TurnHandle {
    /// Builds a [`CorrelationCtx`] carrying this handle's captured trace and
    /// span identifiers, leaving the remaining fields at their `None` default.
    fn correlation(&self) -> CorrelationCtx {
        CorrelationCtx {
            trace_id: self.trace_id.clone(),
            span_id: self.span_id.clone(),
            ..CorrelationCtx::default()
        }
    }

    /// Creates a new handle and immediately publishes [`TurnEvent::Started`].
    ///
    /// `session_id` and `turn_id` together uniquely identify the turn across
    /// all events emitted by this handle.  The `trace_id` and `span_id` fields
    /// are captured from the active `OTel` span at call time.
    #[must_use]
    pub fn start(
        session_id: impl Into<String>,
        turn_id: impl Into<String>,
        dispatcher: Arc<Dispatcher>,
    ) -> Self {
        let session_id = session_id.into();
        let turn_id = turn_id.into();
        let (trace_id, span_id) = current_span_ids();

        dispatcher.publish(TurnEvent::Started {
            session_id: session_id.clone(),
            turn_id: turn_id.clone(),
            correlation: CorrelationCtx {
                trace_id: trace_id.clone(),
                span_id: span_id.clone(),
                ..CorrelationCtx::default()
            },
        });

        Self {
            session_id,
            turn_id,
            dispatcher,
            trace_id,
            span_id,
        }
    }

    /// Publishes a [`TurnEvent::ToolCalled`] event.
    ///
    /// Call this each time a tool is invoked during the turn.
    ///
    /// # Parameters
    ///
    /// * `tool_name` — name of the tool being invoked (e.g. `"bash"`).
    /// * `input_summary` — short description of the input for observability.
    /// * `tool_call_id` — opaque correlation ID generated by the caller (e.g. a
    ///   UUID). Pass the same value to the matching `AuditEvent::tool_call_id`
    ///   so tool-call/result pairs can be correlated in the audit log.
    pub fn tool_called(
        &self,
        tool_name: impl Into<String>,
        input_summary: impl Into<String>,
        tool_call_id: Option<String>,
    ) {
        self.dispatcher.publish(TurnEvent::ToolCalled {
            tool_name: tool_name.into(),
            input_summary: input_summary.into(),
            turn_id: Some(self.turn_id.clone()),
            correlation: self.correlation(),
            tool_call_id,
        });
    }

    /// Publishes a [`TurnEvent::AssistantDelta`] event.
    ///
    /// Call this for each incremental text chunk produced by the assistant
    /// during streaming.
    pub fn delta(&self, content: impl Into<String>) {
        self.dispatcher.publish(TurnEvent::AssistantDelta {
            content: content.into(),
            turn_id: Some(self.turn_id.clone()),
            correlation: self.correlation(),
        });
    }

    /// Publishes [`TurnEvent::Completed`] and consumes the handle.
    ///
    /// `output_tokens` is the number of tokens generated during this turn.
    pub fn complete(self, output_tokens: u32) {
        self.dispatcher.publish(TurnEvent::Completed {
            session_id: self.session_id,
            turn_id: self.turn_id,
            output_tokens,
            input_tokens: None,
            traceparent: None,
            correlation: CorrelationCtx {
                trace_id: self.trace_id,
                span_id: self.span_id,
                ..CorrelationCtx::default()
            },
        });
    }

    /// Publishes [`TurnEvent::Failed`] and consumes the handle.
    ///
    /// `reason` is a human-readable explanation of the failure.
    pub fn fail(self, reason: impl Into<String>) {
        self.dispatcher.publish(TurnEvent::Failed {
            session_id: self.session_id,
            turn_id: self.turn_id,
            reason: reason.into(),
            correlation: CorrelationCtx {
                trace_id: self.trace_id,
                span_id: self.span_id,
                ..CorrelationCtx::default()
            },
        });
    }
}
